### ISSUE TITLE
Unknown argument: sample

### ISSUE THREAD

**Issue by shadoath** [mongodb-js/mongodb-schema#168]
Attempting to run: `mongodb-schema localhost:27017 prendacoins.users --sample 10000` 
Prints out help and the notice `Unknown argument: sample`

`mongodb-schema --version` => 9.0.0

**Comment by addaleax** [comment]
I guess using `--number 10000` would give you what you are looking for? This is probably mostly a question of updating the readme here?

**Comment by shadoath** [comment]
That worked as I expected! Thank you.
