### ISSUE TITLE
parseSchema is not a function

### ISSUE THREAD

**Issue by AmanKaushik04** [mongodb-js/mongodb-schema#197]
Hey!

I'm trying to follow the example given in ReadMe:

```
const parseSchema = require('mongodb-schema');
const { MongoClient } = require('mongodb');

const dbName = 'test';
const uri = `mongodb://localhost:27017/${dbName}`;
const client = new MongoClient(uri);

async function run() {
  try {
    const database = client.db(dbName);
    const documentStream = database.collection('data').find();

    // Here we are passing in a cursor as the first argument. You can
    // also pass in a stream or an array of documents directly.
    const schema = await parseSchema(documentStream);

    console.log(JSON.stringify(schema, null, 2));
  } finally {
    await client.close();
  }
}

run().catch(console.dir);
```

But whenever I run this, I'm always getting:

> TypeError: parseSchema is not a function

Can anyone point out what I'm doing wrong here? Thanks!

**Comment by Anemy** [comment]
Hi @AmanKaushik04 - we recently updated our default exports which make this example fail. I'll make a pr to update it in the README soon, thanks for reporting! 

To fix it you can replace the line
```js
const parseSchema = require('mongodb-schema');
```
with
```js
const { default: parseSchema } = require('mongodb-schema');
```
Thanks again!

**Comment by Anemy** [comment]
Fixed as part of https://github.com/mongodb-js/mongodb-schema/pull/198 
You may have to update to version `11.2.0` for the import to work correctly. Thanks again!

**Comment by AmanKaushik04** [comment]
Hey @Anemy 
Perfect! It is working as expected now. Thanks for the prompt resolution.
