### ISSUE TITLE
schema parsing throws error if document contains 'toString' as a property path

### ISSUE THREAD

**Issue by mongo-J** [mongodb-js/mongodb-schema#211]
Hi,

We are seeing error is thrown when parsing documents containing `toString` in property path including nested property. This error can be observed for mongodb-schema v11+, though it might also be reproduced for versions under. 

Here is a [code sandbox](https://codesandbox.io/p/sandbox/mongodb-schema-bug-repro-ck4mfj?file=%2Fsrc%2Findex.ts%3A8%2C32) for reproduction and the error can be observed from the web console.

![Screenshot 2023-12-15 at 1 37 52 pm](https://github.com/mongodb-js/mongodb-schema/assets/91439783/3cc33eb9-ab14-433c-a991-4b758216ad2f)

**Comment by addaleax** [comment]
Fixed in v12.1.1, thanks for reporting! :+1:

**Comment by mongo-J** [comment]
@addaleax, thank you so much for the quick fix!
